### ISSUE TITLE
int overflow on 32-bit OS

### ISSUE THREAD

**Issue by WhoSoup** [Factom-Asset-Tokens/factom#16] opened 2019-10-21 14:57 UTC
We got reports of pegnetd not compiling on 32-bit Raspbian running on rpi4. Ran it myself and got this error:
```
/go/pkg/mod/github.com/!emyrk/factom@v0.0.0-20191001194233-40c0cdc2f2a0/dblock.go:182:48: constant 274877906993 overflows int
/go/pkg/mod/github.com/!emyrk/factom@v0.0.0-20191001194233-40c0cdc2f2a0/dblock.go:317:14: constant 274877906993 overflows int
/go/pkg/mod/github.com/!emyrk/factom@v0.0.0-20191001194233-40c0cdc2f2a0/eblock.go:283:48: constant 137438953580 overflows int
```

That's @emyrk's fork and the culprit ends up being these lines:
https://github.com/Factom-Asset-Tokens/factom/blob/884670eb0450e1bae60d4d4e8f1d784a291492d8/dblock.go#L152-L158

and 
https://github.com/Factom-Asset-Tokens/factom/blob/884670eb0450e1bae60d4d4e8f1d784a291492d8/eblock.go#L255-L261

Those should be typed `uint64` constants.

**Comment by AdamSLevy** [comment] 2019-10-21 17:00
No those constant should not be typed. They are not overflowing because
constants cannot overflow.

Somewhere those are being assigned to an int or uint and that is where the
problem lies and that is the variable who's type must be changed.

**Comment by AdamSLevy** [comment] 2019-10-21 17:27
Thanks for raising this issue. I need to add 32 bit builds to my testing process.

However, the issue is not with the constants, which have no type and should continue to not be typed, as it allows us to find these bugs better, with a clearer reason from the compiler. 

Constants by default are un-typed and have no size. They may be arbitrarily large and the compiler will handle it.

The issue, which the compiler is appropriately flagging (note that it's not pointing you to the constants but to where they are used), is that `len()` returns int, which on a 32bit system is 32 bits, and we are comparing an int with an untyped constant, so it is defaulting the constant to int, which is causing the overflow. Instead `len()` should be type cast to uint64 on these lines, which would have to happen regardless if the constants were explicitly type uint64.

Fixed in the latest commit on develop.

**Closed by AdamSLevy** 2019-10-21 17:27 UTC
